### ISSUE TITLE
Daemon to remove stale files periodically

### ISSUE THREAD

**Issue by gevorgyana** [smart-online-judge/basic-online-judge#27]
Should clean user files.

ED: 00:00 30 Oct 2020

**Comment by Pilipets** [comment]
This is blocked by issue https://github.com/smart-online-judge/basic-online-judge/issues/40

**Comment by Pilipets** [comment]
We should add a logic to remove data from the DB and Minio, that is stored for more than a defined period.
That must be a go-routine running periodically.

**Comment by Pilipets** [comment]
The fix is coming from PR https://github.com/smart-online-judge/basic-online-judge/pull/86
