### ISSUE TITLE
Come up with the way of synchronized logging.

### ISSUE THREAD

**Issue by Pilipets** [smart-online-judge/basic-online-judge#37]
Currently, we use goroutines, handlers that are called in parallel.

Therefore we have a problem with synchronized output to the error log.
One must investigate and fix it.

There is a respective module for that - logging_wrapper.go.

**Comment by gevorgyana** [comment]
doing now

**Comment by Pilipets** [comment]
According to the documentation mentioned here https://stackoverflow.com/questions/22758911/golang-does-logging-into-file-using-log-println-takes-care-of-concurrent-access, it's already thread-safe - nothing to do here.

**Comment by gevorgyana** [comment]
Well, let me explain.

Logging calls are indeed synchronized, whether the io is buffer or not is of zero importance. 

The only problem may be with this code 
```
func foo() {
  log.Print("foo")
  log.Print("bar")
}
```: `bar` does not necessarily appear after `foo`. We should solve this when we face with such a problem (currently there is none), and we should do it by using a mutex in this `foo` function.
