### ISSUE TITLE
Modify logic to not store UUID as string in the DB, but a numeric value.

### ISSUE THREAD

**Issue by Pilipets** [smart-online-judge/basic-online-judge#39]
That would be more efficient for comparison - see `db_container.go` for the details

**Comment by gevorgyana** [comment]
doing now.

**Comment by gevorgyana** [comment]
We use UUID4. It takes 128 bytes to store that. We can't have an integer with 128 bytes. So the only thing possible is store a sequence of bytes, i.e. string.

**Comment by gevorgyana** [comment]
Closing this.
