### ISSUE TITLE
Rework the directory structure

### ISSUE THREAD

**Issue by gevorgyana** [smart-online-judge/basic-online-judge#62]
- from what I see now, everything we develop is called `api`. No, it is not. We should use the words so that they bare meaning. (e.g. `utils` is clearly internal, it is not API.)
- It is not okay that logging is inside `api`. It just does not make sense.
- `handlers` are really REST controllers. Need to name them accordingly.

We should not make up meanings for words.

Will write more as I work with the code.

**Comment by Pilipets** [comment]
Nice point, agree.

**Comment by Pilipets** [comment]
The fix is done with PR https://github.com/smart-online-judge/basic-online-judge/pull/65
